[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
snafu = "0.8.6"
